name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: pip install meson ninja
    - run: sudo apt-get install -y valac libgee-0.8-dev libgio2.0-cil-dev libjson-glib-dev libxkbcommon-dev
    - run: meson setup builddir/
      env:
        CC: gcc
    - run: meson test -C builddir/ -v
